import {
  OG_SIZE,
  createOGImage
} from '../../../../lib/og-template';
import {
  getAllArticles,
  topicDisplay,
  topicSubtitle
} from '../../../../lib/articles';

export const alt = 'Articles by topic — Hard Problems';
export const size = OG_SIZE;
export const contentType = 'image/png';

type Props = { params: Promise<{ topic: string }> };

// Pre-render one card per distinct topic across all published articles —
// the same set generated by the topic page's generateStaticParams.
export function generateStaticParams() {
  const topics = new Set<string>();
  for (const article of getAllArticles()) {
    for (const t of article.topics) topics.add(t);
  }
  return Array.from(topics).map((topic) => ({ topic }));
}

export default async function Image({ params }: Props) {
  const { topic } = await params;
  return createOGImage({
    title: topicDisplay(topic),
    subtitle: topicSubtitle(topic)
  });
}
